/remote_node:
  ros__parameters:
    # 遥控类型 sbus/gamepad/keyboard/socket/sonnyps2
    type: "gamepad"
    # 端口
    port: "/dev/input/js0"
    # 波特率
    baudrate: 0
    # 1帧数据长度
    data_len: 0
    # 最大量程
    joy_var_max: 32767
    # 最小量程
    joy_var_min: -32767
    # 线速度最大值 单位m/s
    max_x_vel: 0.5
    # 角速度最大值 单位rad/s
    max_w_vel: 1.0
